
/**
 * @author Matthew.Hillery
 *
 *	If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
 *	If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?
 *	NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. 
 *	The use of "and" when writing out numbers is in compliance with British usage.
 */

public class LetterCounts {
	public static void main(String[] args) {
		
		String[] numbers = new String [] {"One                                       "
				,"Two                                      "
				,"Three                                    "
				,"Four                                     "
				,"Five                                     "
				,"Six                                      "
				,"Seven                                    "
				,"Eight                                    "
				,"Nine                                     "
				,"Ten                                      "
				,"Eleven                                   "
				,"Twelve                                   "
				,"Thirteen                                 "
				,"Fourteen                                 "
				,"Fifteen                                  "
				,"Sixteen                                  "
				,"Seventeen                                "
				,"Eighteen                                 "
				,"Nineteen                                 "
				,"Twenty                                   "
				,"Twenty One                               "
				,"Twenty Two                               "
				,"Twenty Three                             "
				,"Twenty Four                              "
				,"Twenty Five                              "
				,"Twenty Six                               "
				,"Twenty Seven                             "
				,"Twenty Eight                             "
				,"Twenty Nine                              "
				,"Thirty                                   "
				,"Thirty One                               "
				,"Thirty Two                               "
				,"Thirty Three                             "
				,"Thirty Four                              "
				,"Thirty Five                              "
				,"Thirty Six                               "
				,"Thirty Seven                             "
				,"Thirty Eight                             "
				,"Thirty Nine                              "
				,"Forty                                    "
				,"Forty One                                "
				,"Forty Two                                "
				,"Forty Three                              "
				,"Forty Four                               "
				,"Forty Five                               "
				,"Forty Six                                "
				,"Forty Seven                              "
				,"Forty Eight                              "
				,"Forty Nine                               "
				,"Fifty                                    "
				,"Fifty One                                "
				,"Fifty Two                                "
				,"Fifty Three                              "
				,"Fifty Four                               "
				,"Fifty Five                               "
				,"Fifty Six                                "
				,"Fifty Seven                              "
				,"Fifty Eight                              "
				,"Fifty Nine                               "
				,"Sixty                                    "
				,"Sixty One                                "
				,"Sixty Two                                "
				,"Sixty Three                              "
				,"Sixty Four                               "
				,"Sixty Five                               "
				,"Sixty Six                                "
				,"Sixty Seven                              "
				,"Sixty Eight                              "
				,"Sixty Nine                               "
				,"Seventy                                  "
				,"Seventy One                              "
				,"Seventy Two                              "
				,"Seventy Three                            "
				,"Seventy Four                             "
				,"Seventy Five                             "
				,"Seventy Six                              "
				,"Seventy Seven                            "
				,"Seventy Eight                            "
				,"Seventy Nine                             "
				,"Eighty                                   "
				,"Eighty One                               "
				,"Eighty Two                               "
				,"Eighty Three                             "
				,"Eighty Four                              "
				,"Eighty Five                              "
				,"Eighty Six                               "
				,"Eighty Seven                             "
				,"Eighty Eight                             "
				,"Eighty Nine                              "
				,"Ninety                                   "
				,"Ninety One                               "
				,"Ninety Two                               "
				,"Ninety Three                             "
				,"Ninety Four                              "
				,"Ninety Five                              "
				,"Ninety Six                               "
				,"Ninety Seven                             "
				,"Ninety Eight                             "
				,"Ninety Nine                              "
				,"One hundred                              "
				,"One hundred andOne                          "
				,"One hundred andTwo                          "
				,"One hundred andThree                        "
				,"One hundred andFour                         "
				,"One hundred andFive                         "
				,"One hundred andSix                          "
				,"One hundred andSeven                        "
				,"One hundred andEight                        "
				,"One hundred andNine                         "
				,"One hundred andTen                          "
				,"One hundred andEleven                       "
				,"One hundred andTwelve                       "
				,"One hundred andThirteen                     "
				,"One hundred andFourteen                     "
				,"One hundred andFifteen                      "
				,"One hundred andSixteen                      "
				,"One hundred andSeventeen                    "
				,"One hundred andEighteen                     "
				,"One hundred andNineteen                     "
				,"One hundred andTwenty                       "
				,"One hundred andTwenty One                   "
				,"One hundred andTwenty Two                   "
				,"One hundred andTwenty Three                 "
				,"One hundred andTwenty Four                  "
				,"One hundred andTwenty Five                  "
				,"One hundred andTwenty Six                   "
				,"One hundred andTwenty Seven                 "
				,"One hundred andTwenty Eight                 "
				,"One hundred andTwenty Nine                  "
				,"One hundred andThirty                       "
				,"One hundred andThirty One                   "
				,"One hundred andThirty Two                   "
				,"One hundred andThirty Three                 "
				,"One hundred andThirty Four                  "
				,"One hundred andThirty Five                  "
				,"One hundred andThirty Six                   "
				,"One hundred andThirty Seven                 "
				,"One hundred andThirty Eight                 "
				,"One hundred andThirty Nine                  "
				,"One hundred andForty                        "
				,"One hundred andForty One                    "
				,"One hundred andForty Two                    "
				,"One hundred andForty Three                  "
				,"One hundred andForty Four                   "
				,"One hundred andForty Five                   "
				,"One hundred andForty Six                    "
				,"One hundred andForty Seven                  "
				,"One hundred andForty Eight                  "
				,"One hundred andForty Nine                   "
				,"One hundred andFifty                        "
				,"One hundred andFifty One                    "
				,"One hundred andFifty Two                    "
				,"One hundred andFifty Three                  "
				,"One hundred andFifty Four                   "
				,"One hundred andFifty Five                   "
				,"One hundred andFifty Six                    "
				,"One hundred andFifty Seven                  "
				,"One hundred andFifty Eight                  "
				,"One hundred andFifty Nine                   "
				,"One hundred andSixty                        "
				,"One hundred andSixty One                    "
				,"One hundred andSixty Two                    "
				,"One hundred andSixty Three                  "
				,"One hundred andSixty Four                   "
				,"One hundred andSixty Five                   "
				,"One hundred andSixty Six                    "
				,"One hundred andSixty Seven                  "
				,"One hundred andSixty Eight                  "
				,"One hundred andSixty Nine                   "
				,"One hundred andSeventy                      "
				,"One hundred andSeventy One                  "
				,"One hundred andSeventy Two                  "
				,"One hundred andSeventy Three                "
				,"One hundred andSeventy Four                 "
				,"One hundred andSeventy Five                 "
				,"One hundred andSeventy Six                  "
				,"One hundred andSeventy Seven                "
				,"One hundred andSeventy Eight                "
				,"One hundred andSeventy Nine                 "
				,"One hundred andEighty                       "
				,"One hundred andEighty One                   "
				,"One hundred andEighty Two                   "
				,"One hundred andEighty Three                 "
				,"One hundred andEighty Four                  "
				,"One hundred andEighty Five                  "
				,"One hundred andEighty Six                   "
				,"One hundred andEighty Seven                 "
				,"One hundred andEighty Eight                 "
				,"One hundred andEighty Nine                  "
				,"One hundred andNinety                       "
				,"One hundred andNinety One                   "
				,"One hundred andNinety Two                   "
				,"One hundred andNinety Three                 "
				,"One hundred andNinety Four                  "
				,"One hundred andNinety Five                  "
				,"One hundred andNinety Six                   "
				,"One hundred andNinety Seven                 "
				,"One hundred andNinety Eight                 "
				,"One hundred andNinety Nine                  "
				,"Two hundred                             "
				,"Two hundred andOne                          "
				,"Two hundred andTwo                          "
				,"Two hundred andThree                        "
				,"Two hundred andFour                         "
				,"Two hundred andFive                         "
				,"Two hundred andSix                          "
				,"Two hundred andSeven                        "
				,"Two hundred andEight                        "
				,"Two hundred andNine                         "
				,"Two hundred andTen                          "
				,"Two hundred andEleven                       "
				,"Two hundred andTwelve                       "
				,"Two hundred andThirteen                     "
				,"Two hundred andFourteen                     "
				,"Two hundred andFifteen                      "
				,"Two hundred andSixteen                      "
				,"Two hundred andSeventeen                    "
				,"Two hundred andEighteen                     "
				,"Two hundred andNineteen                     "
				,"Two hundred andTwenty                       "
				,"Two hundred andTwenty One                   "
				,"Two hundred andTwenty Two                   "
				,"Two hundred andTwenty Three                 "
				,"Two hundred andTwenty Four                  "
				,"Two hundred andTwenty Five                  "
				,"Two hundred andTwenty Six                   "
				,"Two hundred andTwenty Seven                 "
				,"Two hundred andTwenty Eight                 "
				,"Two hundred andTwenty Nine                  "
				,"Two hundred andThirty                       "
				,"Two hundred andThirty One                   "
				,"Two hundred andThirty Two                   "
				,"Two hundred andThirty Three                 "
				,"Two hundred andThirty Four                  "
				,"Two hundred andThirty Five                  "
				,"Two hundred andThirty Six                   "
				,"Two hundred andThirty Seven                 "
				,"Two hundred andThirty Eight                 "
				,"Two hundred andThirty Nine                  "
				,"Two hundred andForty                        "
				,"Two hundred andForty One                    "
				,"Two hundred andForty Two                    "
				,"Two hundred andForty Three                  "
				,"Two hundred andForty Four                   "
				,"Two hundred andForty Five                   "
				,"Two hundred andForty Six                    "
				,"Two hundred andForty Seven                  "
				,"Two hundred andForty Eight                  "
				,"Two hundred andForty Nine                   "
				,"Two hundred andFifty                        "
				,"Two hundred andFifty One                    "
				,"Two hundred andFifty Two                    "
				,"Two hundred andFifty Three                  "
				,"Two hundred andFifty Four                   "
				,"Two hundred andFifty Five                   "
				,"Two hundred andFifty Six                    "
				,"Two hundred andFifty Seven                  "
				,"Two hundred andFifty Eight                  "
				,"Two hundred andFifty Nine                   "
				,"Two hundred andSixty                        "
				,"Two hundred andSixty One                    "
				,"Two hundred andSixty Two                    "
				,"Two hundred andSixty Three                  "
				,"Two hundred andSixty Four                   "
				,"Two hundred andSixty Five                   "
				,"Two hundred andSixty Six                    "
				,"Two hundred andSixty Seven                  "
				,"Two hundred andSixty Eight                  "
				,"Two hundred andSixty Nine                   "
				,"Two hundred andSeventy                      "
				,"Two hundred andSeventy One                  "
				,"Two hundred andSeventy Two                  "
				,"Two hundred andSeventy Three                "
				,"Two hundred andSeventy Four                 "
				,"Two hundred andSeventy Five                 "
				,"Two hundred andSeventy Six                  "
				,"Two hundred andSeventy Seven                "
				,"Two hundred andSeventy Eight                "
				,"Two hundred andSeventy Nine                 "
				,"Two hundred andEighty                       "
				,"Two hundred andEighty One                   "
				,"Two hundred andEighty Two                   "
				,"Two hundred andEighty Three                 "
				,"Two hundred andEighty Four                  "
				,"Two hundred andEighty Five                  "
				,"Two hundred andEighty Six                   "
				,"Two hundred andEighty Seven                 "
				,"Two hundred andEighty Eight                 "
				,"Two hundred andEighty Nine                  "
				,"Two hundred andNinety                       "
				,"Two hundred andNinety One                   "
				,"Two hundred andNinety Two                   "
				,"Two hundred andNinety Three                 "
				,"Two hundred andNinety Four                  "
				,"Two hundred andNinety Five                  "
				,"Two hundred andNinety Six                   "
				,"Two hundred andNinety Seven                 "
				,"Two hundred andNinety Eight                 "
				,"Two hundred andNinety Nine                  "
				,"Three hundred                         "
				,"Three hundred andOne                        "
				,"Three hundred andTwo                        "
				,"Three hundred andThree                      "
				,"Three hundred andFour                       "
				,"Three hundred andFive                       "
				,"Three hundred andSix                        "
				,"Three hundred andSeven                      "
				,"Three hundred andEight                      "
				,"Three hundred andNine                       "
				,"Three hundred andTen                        "
				,"Three hundred andEleven                     "
				,"Three hundred andTwelve                     "
				,"Three hundred andThirteen                   "
				,"Three hundred andFourteen                   "
				,"Three hundred andFifteen                    "
				,"Three hundred andSixteen                    "
				,"Three hundred andSeventeen                  "
				,"Three hundred andEighteen                   "
				,"Three hundred andNineteen                   "
				,"Three hundred andTwenty                     "
				,"Three hundred andTwenty One                 "
				,"Three hundred andTwenty Two                 "
				,"Three hundred andTwenty Three               "
				,"Three hundred andTwenty Four                "
				,"Three hundred andTwenty Five                "
				,"Three hundred andTwenty Six                 "
				,"Three hundred andTwenty Seven               "
				,"Three hundred andTwenty Eight               "
				,"Three hundred andTwenty Nine                "
				,"Three hundred andThirty                     "
				,"Three hundred andThirty One                 "
				,"Three hundred andThirty Two                 "
				,"Three hundred andThirty Three               "
				,"Three hundred andThirty Four                "
				,"Three hundred andThirty Five                "
				,"Three hundred andThirty Six                 "
				,"Three hundred andThirty Seven               "
				,"Three hundred andThirty Eight               "
				,"Three hundred andThirty Nine                "
				,"Three hundred andForty                      "
				,"Three hundred andForty One                  "
				,"Three hundred andForty Two                  "
				,"Three hundred andForty Three                "
				,"Three hundred andForty Four                 "
				,"Three hundred andForty Five                 "
				,"Three hundred andForty Six                  "
				,"Three hundred andForty Seven                "
				,"Three hundred andForty Eight                "
				,"Three hundred andForty Nine                 "
				,"Three hundred andFifty                      "
				,"Three hundred andFifty One                  "
				,"Three hundred andFifty Two                  "
				,"Three hundred andFifty Three                "
				,"Three hundred andFifty Four                 "
				,"Three hundred andFifty Five                 "
				,"Three hundred andFifty Six                  "
				,"Three hundred andFifty Seven                "
				,"Three hundred andFifty Eight                "
				,"Three hundred andFifty Nine                 "
				,"Three hundred andSixty                      "
				,"Three hundred andSixty One                  "
				,"Three hundred andSixty Two                  "
				,"Three hundred andSixty Three                "
				,"Three hundred andSixty Four                 "
				,"Three hundred andSixty Five                 "
				,"Three hundred andSixty Six                  "
				,"Three hundred andSixty Seven                "
				,"Three hundred andSixty Eight                "
				,"Three hundred andSixty Nine                 "
				,"Three hundred andSeventy                    "
				,"Three hundred andSeventy One                "
				,"Three hundred andSeventy Two                "
				,"Three hundred andSeventy Three              "
				,"Three hundred andSeventy Four               "
				,"Three hundred andSeventy Five               "
				,"Three hundred andSeventy Six                "
				,"Three hundred andSeventy Seven              "
				,"Three hundred andSeventy Eight              "
				,"Three hundred andSeventy Nine               "
				,"Three hundred andEighty                     "
				,"Three hundred andEighty One                 "
				,"Three hundred andEighty Two                 "
				,"Three hundred andEighty Three               "
				,"Three hundred andEighty Four                "
				,"Three hundred andEighty Five                "
				,"Three hundred andEighty Six                 "
				,"Three hundred andEighty Seven               "
				,"Three hundred andEighty Eight               "
				,"Three hundred andEighty Nine                "
				,"Three hundred andNinety                     "
				,"Three hundred andNinety One                 "
				,"Three hundred andNinety Two                 "
				,"Three hundred andNinety Three               "
				,"Three hundred andNinety Four                "
				,"Three hundred andNinety Five                "
				,"Three hundred andNinety Six                 "
				,"Three hundred andNinety Seven               "
				,"Three hundred andNinety Eight               "
				,"Three hundred andNinety Nine                "
				,"Four hundred                            "
				,"Four hundred andOne                         "
				,"Four hundred andTwo                         "
				,"Four hundred andThree                       "
				,"Four hundred andFour                        "
				,"Four hundred andFive                        "
				,"Four hundred andSix                         "
				,"Four hundred andSeven                       "
				,"Four hundred andEight                       "
				,"Four hundred andNine                        "
				,"Four hundred andTen                         "
				,"Four hundred andEleven                      "
				,"Four hundred andTwelve                      "
				,"Four hundred andThirteen                    "
				,"Four hundred andFourteen                    "
				,"Four hundred andFifteen                     "
				,"Four hundred andSixteen                     "
				,"Four hundred andSeventeen                   "
				,"Four hundred andEighteen                    "
				,"Four hundred andNineteen                    "
				,"Four hundred andTwenty                      "
				,"Four hundred andTwenty One                  "
				,"Four hundred andTwenty Two                  "
				,"Four hundred andTwenty Three                "
				,"Four hundred andTwenty Four                 "
				,"Four hundred andTwenty Five                 "
				,"Four hundred andTwenty Six                  "
				,"Four hundred andTwenty Seven                "
				,"Four hundred andTwenty Eight                "
				,"Four hundred andTwenty Nine                 "
				,"Four hundred andThirty                      "
				,"Four hundred andThirty One                  "
				,"Four hundred andThirty Two                  "
				,"Four hundred andThirty Three                "
				,"Four hundred andThirty Four                 "
				,"Four hundred andThirty Five                 "
				,"Four hundred andThirty Six                  "
				,"Four hundred andThirty Seven                "
				,"Four hundred andThirty Eight                "
				,"Four hundred andThirty Nine                 "
				,"Four hundred andForty                       "
				,"Four hundred andForty One                   "
				,"Four hundred andForty Two                   "
				,"Four hundred andForty Three                 "
				,"Four hundred andForty Four                  "
				,"Four hundred andForty Five                  "
				,"Four hundred andForty Six                   "
				,"Four hundred andForty Seven                 "
				,"Four hundred andForty Eight                 "
				,"Four hundred andForty Nine                  "
				,"Four hundred andFifty                       "
				,"Four hundred andFifty One                   "
				,"Four hundred andFifty Two                   "
				,"Four hundred andFifty Three                 "
				,"Four hundred andFifty Four                  "
				,"Four hundred andFifty Five                  "
				,"Four hundred andFifty Six                   "
				,"Four hundred andFifty Seven                 "
				,"Four hundred andFifty Eight                 "
				,"Four hundred andFifty Nine                  "
				,"Four hundred andSixty                       "
				,"Four hundred andSixty One                   "
				,"Four hundred andSixty Two                   "
				,"Four hundred andSixty Three                 "
				,"Four hundred andSixty Four                  "
				,"Four hundred andSixty Five                  "
				,"Four hundred andSixty Six                   "
				,"Four hundred andSixty Seven                 "
				,"Four hundred andSixty Eight                 "
				,"Four hundred andSixty Nine                  "
				,"Four hundred andSeventy                     "
				,"Four hundred andSeventy One                 "
				,"Four hundred andSeventy Two                 "
				,"Four hundred andSeventy Three               "
				,"Four hundred andSeventy Four                "
				,"Four hundred andSeventy Five                "
				,"Four hundred andSeventy Six                 "
				,"Four hundred andSeventy Seven               "
				,"Four hundred andSeventy Eight               "
				,"Four hundred andSeventy Nine                "
				,"Four hundred andEighty                      "
				,"Four hundred andEighty One                  "
				,"Four hundred andEighty Two                  "
				,"Four hundred andEighty Three                "
				,"Four hundred andEighty Four                 "
				,"Four hundred andEighty Five                 "
				,"Four hundred andEighty Six                  "
				,"Four hundred andEighty Seven                "
				,"Four hundred andEighty Eight                "
				,"Four hundred andEighty Nine                 "
				,"Four hundred andNinety                      "
				,"Four hundred andNinety One                  "
				,"Four hundred andNinety Two                  "
				,"Four hundred andNinety Three                "
				,"Four hundred andNinety Four                 "
				,"Four hundred andNinety Five                 "
				,"Four hundred andNinety Six                  "
				,"Four hundred andNinety Seven                "
				,"Four hundred andNinety Eight                "
				,"Four hundred andNinety Nine                 "
				,"Five hundred                           "
				,"Five hundred andOne                         "
				,"Five hundred andTwo                         "
				,"Five hundred andThree                       "
				,"Five hundred andFour                        "
				,"Five hundred andFive                        "
				,"Five hundred andSix                         "
				,"Five hundred andSeven                       "
				,"Five hundred andEight                       "
				,"Five hundred andNine                        "
				,"Five hundred andTen                         "
				,"Five hundred andEleven                      "
				,"Five hundred andTwelve                      "
				,"Five hundred andThirteen                    "
				,"Five hundred andFourteen                    "
				,"Five hundred andFifteen                     "
				,"Five hundred andSixteen                     "
				,"Five hundred andSeventeen                   "
				,"Five hundred andEighteen                    "
				,"Five hundred andNineteen                    "
				,"Five hundred andTwenty                      "
				,"Five hundred andTwenty One                  "
				,"Five hundred andTwenty Two                  "
				,"Five hundred andTwenty Three                "
				,"Five hundred andTwenty Four                 "
				,"Five hundred andTwenty Five                 "
				,"Five hundred andTwenty Six                  "
				,"Five hundred andTwenty Seven                "
				,"Five hundred andTwenty Eight                "
				,"Five hundred andTwenty Nine                 "
				,"Five hundred andThirty                      "
				,"Five hundred andThirty One                  "
				,"Five hundred andThirty Two                  "
				,"Five hundred andThirty Three                "
				,"Five hundred andThirty Four                 "
				,"Five hundred andThirty Five                 "
				,"Five hundred andThirty Six                  "
				,"Five hundred andThirty Seven                "
				,"Five hundred andThirty Eight                "
				,"Five hundred andThirty Nine                 "
				,"Five hundred andForty                       "
				,"Five hundred andForty One                   "
				,"Five hundred andForty Two                   "
				,"Five hundred andForty Three                 "
				,"Five hundred andForty Four                  "
				,"Five hundred andForty Five                  "
				,"Five hundred andForty Six                   "
				,"Five hundred andForty Seven                 "
				,"Five hundred andForty Eight                 "
				,"Five hundred andForty Nine                  "
				,"Five hundred andFifty                       "
				,"Five hundred andFifty One                   "
				,"Five hundred andFifty Two                   "
				,"Five hundred andFifty Three                 "
				,"Five hundred andFifty Four                  "
				,"Five hundred andFifty Five                  "
				,"Five hundred andFifty Six                   "
				,"Five hundred andFifty Seven                 "
				,"Five hundred andFifty Eight                 "
				,"Five hundred andFifty Nine                  "
				,"Five hundred andSixty                       "
				,"Five hundred andSixty One                   "
				,"Five hundred andSixty Two                   "
				,"Five hundred andSixty Three                 "
				,"Five hundred andSixty Four                  "
				,"Five hundred andSixty Five                  "
				,"Five hundred andSixty Six                   "
				,"Five hundred andSixty Seven                 "
				,"Five hundred andSixty Eight                 "
				,"Five hundred andSixty Nine                  "
				,"Five hundred andSeventy                     "
				,"Five hundred andSeventy One                 "
				,"Five hundred andSeventy Two                 "
				,"Five hundred andSeventy Three               "
				,"Five hundred andSeventy Four                "
				,"Five hundred andSeventy Five                "
				,"Five hundred andSeventy Six                 "
				,"Five hundred andSeventy Seven               "
				,"Five hundred andSeventy Eight               "
				,"Five hundred andSeventy Nine                "
				,"Five hundred andEighty                      "
				,"Five hundred andEighty One                  "
				,"Five hundred andEighty Two                  "
				,"Five hundred andEighty Three                "
				,"Five hundred andEighty Four                 "
				,"Five hundred andEighty Five                 "
				,"Five hundred andEighty Six                  "
				,"Five hundred andEighty Seven                "
				,"Five hundred andEighty Eight                "
				,"Five hundred andEighty Nine                 "
				,"Five hundred andNinety                      "
				,"Five hundred andNinety One                  "
				,"Five hundred andNinety Two                  "
				,"Five hundred andNinety Three                "
				,"Five hundred andNinety Four                 "
				,"Five hundred andNinety Five                 "
				,"Five hundred andNinety Six                  "
				,"Five hundred andNinety Seven                "
				,"Five hundred andNinety Eight                "
				,"Five hundred andNinety Nine                 "
				,"Six hundred                            "
				,"Six hundred andOne                          "
				,"Six hundred andTwo                          "
				,"Six hundred andThree                        "
				,"Six hundred andFour                         "
				,"Six hundred andFive                         "
				,"Six hundred andSix                          "
				,"Six hundred andSeven                        "
				,"Six hundred andEight                        "
				,"Six hundred andNine                         "
				,"Six hundred andTen                          "
				,"Six hundred andEleven                       "
				,"Six hundred andTwelve                       "
				,"Six hundred andThirteen                     "
				,"Six hundred andFourteen                     "
				,"Six hundred andFifteen                      "
				,"Six hundred andSixteen                      "
				,"Six hundred andSeventeen                    "
				,"Six hundred andEighteen                     "
				,"Six hundred andNineteen                     "
				,"Six hundred andTwenty                       "
				,"Six hundred andTwenty One                   "
				,"Six hundred andTwenty Two                   "
				,"Six hundred andTwenty Three                 "
				,"Six hundred andTwenty Four                  "
				,"Six hundred andTwenty Five                  "
				,"Six hundred andTwenty Six                   "
				,"Six hundred andTwenty Seven                 "
				,"Six hundred andTwenty Eight                 "
				,"Six hundred andTwenty Nine                  "
				,"Six hundred andThirty                       "
				,"Six hundred andThirty One                   "
				,"Six hundred andThirty Two                   "
				,"Six hundred andThirty Three                 "
				,"Six hundred andThirty Four                  "
				,"Six hundred andThirty Five                  "
				,"Six hundred andThirty Six                   "
				,"Six hundred andThirty Seven                 "
				,"Six hundred andThirty Eight                 "
				,"Six hundred andThirty Nine                  "
				,"Six hundred andForty                        "
				,"Six hundred andForty One                    "
				,"Six hundred andForty Two                    "
				,"Six hundred andForty Three                  "
				,"Six hundred andForty Four                   "
				,"Six hundred andForty Five                   "
				,"Six hundred andForty Six                    "
				,"Six hundred andForty Seven                  "
				,"Six hundred andForty Eight                  "
				,"Six hundred andForty Nine                   "
				,"Six hundred andFifty                        "
				,"Six hundred andFifty One                    "
				,"Six hundred andFifty Two                    "
				,"Six hundred andFifty Three                  "
				,"Six hundred andFifty Four                   "
				,"Six hundred andFifty Five                   "
				,"Six hundred andFifty Six                    "
				,"Six hundred andFifty Seven                  "
				,"Six hundred andFifty Eight                  "
				,"Six hundred andFifty Nine                   "
				,"Six hundred andSixty                        "
				,"Six hundred andSixty One                    "
				,"Six hundred andSixty Two                    "
				,"Six hundred andSixty Three                  "
				,"Six hundred andSixty Four                   "
				,"Six hundred andSixty Five                   "
				,"Six hundred andSixty Six                    "
				,"Six hundred andSixty Seven                  "
				,"Six hundred andSixty Eight                  "
				,"Six hundred andSixty Nine                   "
				,"Six hundred andSeventy                      "
				,"Six hundred andSeventy One                  "
				,"Six hundred andSeventy Two                  "
				,"Six hundred andSeventy Three                "
				,"Six hundred andSeventy Four                 "
				,"Six hundred andSeventy Five                 "
				,"Six hundred andSeventy Six                  "
				,"Six hundred andSeventy Seven                "
				,"Six hundred andSeventy Eight                "
				,"Six hundred andSeventy Nine                 "
				,"Six hundred andEighty                       "
				,"Six hundred andEighty One                   "
				,"Six hundred andEighty Two                   "
				,"Six hundred andEighty Three                 "
				,"Six hundred andEighty Four                  "
				,"Six hundred andEighty Five                  "
				,"Six hundred andEighty Six                   "
				,"Six hundred andEighty Seven                 "
				,"Six hundred andEighty Eight                 "
				,"Six hundred andEighty Nine                  "
				,"Six hundred andNinety                       "
				,"Six hundred andNinety One                   "
				,"Six hundred andNinety Two                   "
				,"Six hundred andNinety Three                 "
				,"Six hundred andNinety Four                  "
				,"Six hundred andNinety Five                  "
				,"Six hundred andNinety Six                   "
				,"Six hundred andNinety Seven                 "
				,"Six hundred andNinety Eight                 "
				,"Six hundred andNinety Nine                  "
				,"Seven hundred                           "
				,"Seven hundred andOne                        "
				,"Seven hundred andTwo                        "
				,"Seven hundred andThree                      "
				,"Seven hundred andFour                       "
				,"Seven hundred andFive                       "
				,"Seven hundred andSix                        "
				,"Seven hundred andSeven                      "
				,"Seven hundred andEight                      "
				,"Seven hundred andNine                       "
				,"Seven hundred andTen                        "
				,"Seven hundred andEleven                     "
				,"Seven hundred andTwelve                     "
				,"Seven hundred andThirteen                   "
				,"Seven hundred andFourteen                   "
				,"Seven hundred andFifteen                    "
				,"Seven hundred andSixteen                    "
				,"Seven hundred andSeventeen                  "
				,"Seven hundred andEighteen                   "
				,"Seven hundred andNineteen                   "
				,"Seven hundred andTwenty                     "
				,"Seven hundred andTwenty One                 "
				,"Seven hundred andTwenty Two                 "
				,"Seven hundred andTwenty Three               "
				,"Seven hundred andTwenty Four                "
				,"Seven hundred andTwenty Five                "
				,"Seven hundred andTwenty Six                 "
				,"Seven hundred andTwenty Seven               "
				,"Seven hundred andTwenty Eight               "
				,"Seven hundred andTwenty Nine                "
				,"Seven hundred andThirty                     "
				,"Seven hundred andThirty One                 "
				,"Seven hundred andThirty Two                 "
				,"Seven hundred andThirty Three               "
				,"Seven hundred andThirty Four                "
				,"Seven hundred andThirty Five                "
				,"Seven hundred andThirty Six                 "
				,"Seven hundred andThirty Seven               "
				,"Seven hundred andThirty Eight               "
				,"Seven hundred andThirty Nine                "
				,"Seven hundred andForty                      "
				,"Seven hundred andForty One                  "
				,"Seven hundred andForty Two                  "
				,"Seven hundred andForty Three                "
				,"Seven hundred andForty Four                 "
				,"Seven hundred andForty Five                 "
				,"Seven hundred andForty Six                  "
				,"Seven hundred andForty Seven                "
				,"Seven hundred andForty Eight                "
				,"Seven hundred andForty Nine                 "
				,"Seven hundred andFifty                      "
				,"Seven hundred andFifty One                  "
				,"Seven hundred andFifty Two                  "
				,"Seven hundred andFifty Three                "
				,"Seven hundred andFifty Four                 "
				,"Seven hundred andFifty Five                 "
				,"Seven hundred andFifty Six                  "
				,"Seven hundred andFifty Seven                "
				,"Seven hundred andFifty Eight                "
				,"Seven hundred andFifty Nine                 "
				,"Seven hundred andSixty                      "
				,"Seven hundred andSixty One                  "
				,"Seven hundred andSixty Two                  "
				,"Seven hundred andSixty Three                "
				,"Seven hundred andSixty Four                 "
				,"Seven hundred andSixty Five                 "
				,"Seven hundred andSixty Six                  "
				,"Seven hundred andSixty Seven                "
				,"Seven hundred andSixty Eight                "
				,"Seven hundred andSixty Nine                 "
				,"Seven hundred andSeventy                    "
				,"Seven hundred andSeventy One                "
				,"Seven hundred andSeventy Two                "
				,"Seven hundred andSeventy Three              "
				,"Seven hundred andSeventy Four               "
				,"Seven hundred andSeventy Five               "
				,"Seven hundred andSeventy Six                "
				,"Seven hundred andSeventy Seven              "
				,"Seven hundred andSeventy Eight              "
				,"Seven hundred andSeventy Nine               "
				,"Seven hundred andEighty                     "
				,"Seven hundred andEighty One                 "
				,"Seven hundred andEighty Two                 "
				,"Seven hundred andEighty Three               "
				,"Seven hundred andEighty Four                "
				,"Seven hundred andEighty Five                "
				,"Seven hundred andEighty Six                 "
				,"Seven hundred andEighty Seven               "
				,"Seven hundred andEighty Eight               "
				,"Seven hundred andEighty Nine                "
				,"Seven hundred andNinety                     "
				,"Seven hundred andNinety One                 "
				,"Seven hundred andNinety Two                 "
				,"Seven hundred andNinety Three               "
				,"Seven hundred andNinety Four                "
				,"Seven hundred andNinety Five                "
				,"Seven hundred andNinety Six                 "
				,"Seven hundred andNinety Seven               "
				,"Seven hundred andNinety Eight               "
				,"Seven hundred andNinety Nine                "
				,"Eight hundred                            "
				,"Eight hundred andOne                        "
				,"Eight hundred andTwo                        "
				,"Eight hundred andThree                      "
				,"Eight hundred andFour                       "
				,"Eight hundred andFive                       "
				,"Eight hundred andSix                        "
				,"Eight hundred andSeven                      "
				,"Eight hundred andEight                      "
				,"Eight hundred andNine                       "
				,"Eight hundred andTen                        "
				,"Eight hundred andEleven                     "
				,"Eight hundred andTwelve                     "
				,"Eight hundred andThirteen                   "
				,"Eight hundred andFourteen                   "
				,"Eight hundred andFifteen                    "
				,"Eight hundred andSixteen                    "
				,"Eight hundred andSeventeen                  "
				,"Eight hundred andEighteen                   "
				,"Eight hundred andNineteen                   "
				,"Eight hundred andTwenty                     "
				,"Eight hundred andTwenty One                 "
				,"Eight hundred andTwenty Two                 "
				,"Eight hundred andTwenty Three               "
				,"Eight hundred andTwenty Four                "
				,"Eight hundred andTwenty Five                "
				,"Eight hundred andTwenty Six                 "
				,"Eight hundred andTwenty Seven               "
				,"Eight hundred andTwenty Eight               "
				,"Eight hundred andTwenty Nine                "
				,"Eight hundred andThirty                     "
				,"Eight hundred andThirty One                 "
				,"Eight hundred andThirty Two                 "
				,"Eight hundred andThirty Three               "
				,"Eight hundred andThirty Four                "
				,"Eight hundred andThirty Five                "
				,"Eight hundred andThirty Six                 "
				,"Eight hundred andThirty Seven               "
				,"Eight hundred andThirty Eight               "
				,"Eight hundred andThirty Nine                "
				,"Eight hundred andForty                      "
				,"Eight hundred andForty One                  "
				,"Eight hundred andForty Two                  "
				,"Eight hundred andForty Three                "
				,"Eight hundred andForty Four                 "
				,"Eight hundred andForty Five                 "
				,"Eight hundred andForty Six                  "
				,"Eight hundred andForty Seven                "
				,"Eight hundred andForty Eight                "
				,"Eight hundred andForty Nine                 "
				,"Eight hundred andFifty                      "
				,"Eight hundred andFifty One                  "
				,"Eight hundred andFifty Two                  "
				,"Eight hundred andFifty Three                "
				,"Eight hundred andFifty Four                 "
				,"Eight hundred andFifty Five                 "
				,"Eight hundred andFifty Six                  "
				,"Eight hundred andFifty Seven                "
				,"Eight hundred andFifty Eight                "
				,"Eight hundred andFifty Nine                 "
				,"Eight hundred andSixty                      "
				,"Eight hundred andSixty One                  "
				,"Eight hundred andSixty Two                  "
				,"Eight hundred andSixty Three                "
				,"Eight hundred andSixty Four                 "
				,"Eight hundred andSixty Five                 "
				,"Eight hundred andSixty Six                  "
				,"Eight hundred andSixty Seven                "
				,"Eight hundred andSixty Eight                "
				,"Eight hundred andSixty Nine                 "
				,"Eight hundred andSeventy                    "
				,"Eight hundred andSeventy One                "
				,"Eight hundred andSeventy Two                "
				,"Eight hundred andSeventy Three              "
				,"Eight hundred andSeventy Four               "
				,"Eight hundred andSeventy Five               "
				,"Eight hundred andSeventy Six                "
				,"Eight hundred andSeventy Seven              "
				,"Eight hundred andSeventy Eight              "
				,"Eight hundred andSeventy Nine               "
				,"Eight hundred andEighty                     "
				,"Eight hundred andEighty One                 "
				,"Eight hundred andEighty Two                 "
				,"Eight hundred andEighty Three               "
				,"Eight hundred andEighty Four                "
				,"Eight hundred andEighty Five                "
				,"Eight hundred andEighty Six                 "
				,"Eight hundred andEighty Seven               "
				,"Eight hundred andEighty Eight               "
				,"Eight hundred andEighty Nine                "
				,"Eight hundred andNinety                     "
				,"Eight hundred andNinety One                 "
				,"Eight hundred andNinety Two                 "
				,"Eight hundred andNinety Three               "
				,"Eight hundred andNinety Four                "
				,"Eight hundred andNinety Five                "
				,"Eight hundred andNinety Six                 "
				,"Eight hundred andNinety Seven               "
				,"Eight hundred andNinety Eight               "
				,"Eight hundred andNinety Nine                "
				,"Nine hundred                         "
				,"Nine hundred andOne                         "
				,"Nine hundred andTwo                         "
				,"Nine hundred andThree                       "
				,"Nine hundred andFour                        "
				,"Nine hundred andFive                        "
				,"Nine hundred andSix                         "
				,"Nine hundred andSeven                       "
				,"Nine hundred andEight                       "
				,"Nine hundred andNine                        "
				,"Nine hundred andTen                         "
				,"Nine hundred andEleven                      "
				,"Nine hundred andTwelve                      "
				,"Nine hundred andThirteen                    "
				,"Nine hundred andFourteen                    "
				,"Nine hundred andFifteen                     "
				,"Nine hundred andSixteen                     "
				,"Nine hundred andSeventeen                   "
				,"Nine hundred andEighteen                    "
				,"Nine hundred andNineteen                    "
				,"Nine hundred andTwenty                      "
				,"Nine hundred andTwenty One                  "
				,"Nine hundred andTwenty Two                  "
				,"Nine hundred andTwenty Three                "
				,"Nine hundred andTwenty Four                 "
				,"Nine hundred andTwenty Five                 "
				,"Nine hundred andTwenty Six                  "
				,"Nine hundred andTwenty Seven                "
				,"Nine hundred andTwenty Eight                "
				,"Nine hundred andTwenty Nine                 "
				,"Nine hundred andThirty                      "
				,"Nine hundred andThirty One                  "
				,"Nine hundred andThirty Two                  "
				,"Nine hundred andThirty Three                "
				,"Nine hundred andThirty Four                 "
				,"Nine hundred andThirty Five                 "
				,"Nine hundred andThirty Six                  "
				,"Nine hundred andThirty Seven                "
				,"Nine hundred andThirty Eight                "
				,"Nine hundred andThirty Nine                 "
				,"Nine hundred andForty                       "
				,"Nine hundred andForty One                   "
				,"Nine hundred andForty Two                   "
				,"Nine hundred andForty Three                 "
				,"Nine hundred andForty Four                  "
				,"Nine hundred andForty Five                  "
				,"Nine hundred andForty Six                   "
				,"Nine hundred andForty Seven                 "
				,"Nine hundred andForty Eight                 "
				,"Nine hundred andForty Nine                  "
				,"Nine hundred andFifty                       "
				,"Nine hundred andFifty One                   "
				,"Nine hundred andFifty Two                   "
				,"Nine hundred andFifty Three                 "
				,"Nine hundred andFifty Four                  "
				,"Nine hundred andFifty Five                  "
				,"Nine hundred andFifty Six                   "
				,"Nine hundred andFifty Seven                 "
				,"Nine hundred andFifty Eight                 "
				,"Nine hundred andFifty Nine                  "
				,"Nine hundred andSixty                       "
				,"Nine hundred andSixty One                   "
				,"Nine hundred andSixty Two                   "
				,"Nine hundred andSixty Three                 "
				,"Nine hundred andSixty Four                  "
				,"Nine hundred andSixty Five                  "
				,"Nine hundred andSixty Six                   "
				,"Nine hundred andSixty Seven                 "
				,"Nine hundred andSixty Eight                 "
				,"Nine hundred andSixty Nine                  "
				,"Nine hundred andSeventy                     "
				,"Nine hundred andSeventy One                 "
				,"Nine hundred andSeventy Two                 "
				,"Nine hundred andSeventy Three               "
				,"Nine hundred andSeventy Four                "
				,"Nine hundred andSeventy Five                "
				,"Nine hundred andSeventy Six                 "
				,"Nine hundred andSeventy Seven               "
				,"Nine hundred andSeventy Eight               "
				,"Nine hundred andSeventy Nine                "
				,"Nine hundred andEighty                      "
				,"Nine hundred andEighty One                  "
				,"Nine hundred andEighty Two                  "
				,"Nine hundred andEighty Three                "
				,"Nine hundred andEighty Four                 "
				,"Nine hundred andEighty Five                 "
				,"Nine hundred andEighty Six                  "
				,"Nine hundred andEighty Seven                "
				,"Nine hundred andEighty Eight                "
				,"Nine hundred andEighty Nine                 "
				,"Nine hundred andNinety                      "
				,"Nine hundred andNinety One                  "
				,"Nine hundred andNinety Two                  "
				,"Nine hundred andNinety Three                "
				,"Nine hundred andNinety Four                 "
				,"Nine hundred andNinety Five                 "
				,"Nine hundred andNinety Six                  "
				,"Nine hundred andNinety Seven                "
				,"Nine hundred andNinety Eight                "
				,"Nine hundred andNinety Nine                 "
				,"One Thousand                             "};
		
		int count = 0;
		
		for (String string : numbers) {
			string = string.replace(" ", "");
			count+=string.length();
		}
		
		System.out.println(count);
		
	}
}

